### ISSUE TITLE
Undefined local variable when using 'knife softlayer server create'

### ISSUE THREAD

**Issue by renier** [softlayer/knife-softlayer#22]
```
/home/selenium/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.25.0/lib/fog/core/attributes.rb:159:in `requires_one': undefined local variable or method `missing' for #<Fog::Compute::Softlayer::Server:0x00000005e99d50> (NameError)
	from /home/selenium/.chefdk/gem/ruby/2.1.0/gems/fog-softlayer-0.3.29/lib/fog/softlayer/models/compute/server.rb:432:in `validate_attributes'
	from /home/selenium/.chefdk/gem/ruby/2.1.0/gems/fog-softlayer-0.3.29/lib/fog/softlayer/models/compute/server.rb:123:in `pre_save'
	from /home/selenium/.chefdk/gem/ruby/2.1.0/gems/fog-softlayer-0.3.29/lib/fog/softlayer/models/compute/server.rb:311:in `save'
	from /home/selenium/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.25.0/lib/fog/core/collection.rb:50:in `create'
	from /home/selenium/.chefdk/gem/ruby/2.1.0/gems/knife-softlayer-0.3.12/lib/chef/knife/softlayer_server_create.rb:299:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:422:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:421:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:51:in `load'
	from /usr/bin/knife:51:in `<main>'
```

gem list | egrep "softlayer|fog" shows:

```
chef-provisioning-fog (0.13.2)
fog (1.29.0)
fog-atmos (0.1.0)
fog-aws (0.1.2)
fog-brightbox (0.7.1)
fog-core (1.30.0, 1.25.0)
fog-ecloud (0.1.1)
fog-json (1.0.1)
fog-local (0.2.1)
fog-powerdns (0.1.1)
fog-profitbricks (0.0.2)
fog-radosgw (0.0.4)
fog-riakcs (0.1.0)
fog-sakuracloud (1.0.1)
fog-serverlove (0.1.2)
fog-softlayer (0.4.5, 0.3.29)
fog-storm_on_demand (0.1.1)
fog-terremark (0.1.0)
fog-vmfusion (0.1.0)
fog-voxel (0.1.0)
fog-xml (0.1.2)
knife-softlayer (0.3.12)
```

**Comment by geemus** [comment]
This was fixed in more recent releases of fog-core with this commit: https://github.com/fog/fog-core/commit/8cee51b886e5db5d007140a1bd26659596da6973. If you update the problem ought to go away.

**Comment by renier** [comment]
Ok, so the problem is that the knife-softlayer is using an old version of fog-softlayer (which uses an old version of fog-core).

https://github.com/fog/fog-softlayer/blob/v0.3.29/fog-softlayer.gemspec
