### ISSUE TITLE
knife softlayer server list

### ISSUE THREAD

**Issue by matburstorm** [softlayer/knife-softlayer#23]
All of the other knife cloud plugins I'm aware of have a server list function to show what's currently running. It would be really nice is softlayer joined the cool kidz.

**Comment by benjsmi** [comment]
This command appears to be implemented to me, but not well:

```# knife softlayer -VV server list
INFO: Using configuration from /root/.chef/knife.rb
Name                 Location Public IP       Private IP      Status    
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-softlayer-1.1.2/lib/fog/softlayer/models/compute/server.rb:219:in `ram=': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.40.0/lib/fog/core/attributes.rb:120:in `block in merge_attributes'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.40.0/lib/fog/core/attributes.rb:117:in `each_pair'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.40.0/lib/fog/core/attributes.rb:117:in `merge_attributes'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.40.0/lib/fog/core/model.rb:20:in `initialize'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-softlayer-1.1.2/lib/fog/softlayer/models/compute/server.rb:55:in `initialize'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.40.0/lib/fog/core/collection.rb:89:in `new'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.40.0/lib/fog/core/collection.rb:89:in `new'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.40.0/lib/fog/core/collection.rb:77:in `block in load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.40.0/lib/fog/core/collection.rb:77:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.40.0/lib/fog/core/collection.rb:77:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-softlayer-1.1.2/lib/fog/softlayer/models/compute/servers.rb:20:in `all'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.40.0/lib/fog/core/collection.rb:113:in `lazy_load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.40.0/lib/fog/core/collection.rb:17:in `each'
	from /root/.chefdk/gem/ruby/2.1.0/gems/knife-softlayer-0.4.3/lib/chef/knife/softlayer_server_list.rb:21:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/application/knife.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:52:in `load'
	from /usr/bin/knife:52:in `<main>'
```
