### ISSUE TITLE
Failing knife softlayer server create --hostname test --domain example.com --flavor tiny -VV

### ISSUE THREAD

**Issue by bhavyaaha** [softlayer/knife-softlayer#36]
1st example in Readme is failing:
<pre><code>
[bhavya@batcave chef-repo]$ knife softlayer server create --hostname test --domain bluecloud.ibm.com --flavor tiny -VV
INFO: Using configuration from /home/bhavya/Documents/IBM/DST/CIO_Portal/code/chef-repo/.chef/knife.rb
Launching SoftLayer VM, this may take a few minutes.
/home/bhavya/.chefdk/gem/ruby/2.1.0/gems/fog-softlayer-0.3.30/lib/fog/softlayer/models/compute/server.rb:418:in `extract_flavor': undefined method `cpu' for nil:NilClass (NoMethodError)
	from /home/bhavya/.chefdk/gem/ruby/2.1.0/gems/fog-softlayer-0.3.30/lib/fog/softlayer/models/compute/server.rb:122:in `pre_save'
	from /home/bhavya/.chefdk/gem/ruby/2.1.0/gems/fog-softlayer-0.3.30/lib/fog/softlayer/models/compute/server.rb:311:in `save'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.32.1/lib/fog/core/collection.rb:51:in `create'
	from /home/bhavya/.chefdk/gem/ruby/2.1.0/gems/knife-softlayer-0.4.0/lib/chef/knife/softlayer_server_create.rb:304:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:405:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:404:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:203:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:54:in `load'
	from /usr/bin/knife:54:in `<main>'
</code></pre>

**Comment by benjsmi** [comment]
This seems to be due to a lack of specifying the ```--cores``` option.
